site_name: My Exam
site_url: https://yurijevs.github.io/exam/
repo_url: https://github.com/yurijevs/exam/
docs_dir: docs
repo_name: yurijevs/exam
edit_uri: edit/master/docs/
nav:
  - Главная: index.md
  - Билет 01.  HTTPS с самоподписанным сертификатом и  фильтрацией трафика: ticket_01.md
  - Билет 02. HTTPS c сертификатом от собственного УЦ: ticket_02.md
  - Билет 03. SMB-сервер в составе домена AD: ticket_03.md
  - Билет 04. Отказоустойчивая конфигурация AD: ticket_04.md
  - Билет 05. Домен AD с фильтрацией трафика: ticket_05.md
  - Билет 06. Прокси-сервер с аутентификацией и  фильтрацией трафика: ticket_06.md
  - Билет 07. Отказоустойчивая конфигурация FreeIPA: ticket_07.md
  - Билет 08. Домен FreeIPA с фильтрацией трафика: ticket_08.md
  - Билет 09. Dynamic DNS: ticket_09.md
  - Билет 10. DNS с репликацией между первичным и вторичным сервером с фильтрацией трафика: ticket_10.md
theme:
  name: material
  icon:
    edit: material/pencil
    view: material/eye
  language: ru
  features:
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
markdown_extensions:
  - smarty
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search:
      enabled: true
      lang:
        - ru
        - en
