site_name: My Exam
site_url: https://exam.yurij.org/
theme:
  name: material
  language: ru
  features:
    - content.code.copy
    - content.code.annotate
markdown_extensions:
  - smarty
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search:
      enabled: true
      lang:
        - ru
        - en